# Generated by Django 2.2.2 on 2019-12-24 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studys', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tsmusersinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='用户名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'TSM用户信息',
                'verbose_name_plural': 'TSM用户信息',
            },
        ),
        migrations.CreateModel(
            name='tsmreceiveinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '预试样已接收'), (1, '正式样已接收'), (2, '已剩余处理'), (3, '未知')], default=0, verbose_name='状态')),
                ('statusdate', models.DateField(verbose_name='状态变更日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('nameorid', models.ForeignKey(default=0, max_length=64, on_delete=django.db.models.deletion.DO_NOTHING, to='project.testarticleinfo', verbose_name='供试品名称/代号')),
                ('operatedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TSM.tsmusersinfo', verbose_name='操作者')),
                ('projectno', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='project.projectinfo', verbose_name='项目编号')),
            ],
            options={
                'verbose_name': 'TSM供试品接收信息',
                'verbose_name_plural': 'TSM供试品接收信息',
                'ordering': ['-update_time'],
            },
        ),
        migrations.CreateModel(
            name='tsmconfstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverydate', models.DateField(verbose_name='领药日期')),
                ('status', models.SmallIntegerField(choices=[(0, '未完成'), (1, '已配待领'), (2, '已领取'), (3, '已返还')], default=0, verbose_name='状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operatedby', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TSM.tsmusersinfo', verbose_name='操作者')),
                ('studyno', models.ForeignKey(default=0, max_length=64, on_delete=django.db.models.deletion.DO_NOTHING, to='studys.studysinfo', verbose_name='专题编号')),
            ],
            options={
                'verbose_name': 'TSM供试品配置状态',
                'verbose_name_plural': 'TSM供试品配置状态表',
                'ordering': ['-update_time'],
            },
        ),
    ]
