# Generated by Django 2.2.2 on 2019-12-24 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patusersinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='用户名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'PAT用户信息',
                'verbose_name_plural': 'PAT用户信息',
            },
        ),
        migrations.CreateModel(
            name='patinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slidespreparationstatus', models.SmallIntegerField(choices=[(0, '未开始'), (1, '制片中'), (2, '制片完成')], default=0, verbose_name='制片状态')),
                ('slidesdate', models.DateField(blank=True, null=True, verbose_name='制片状态变更日期')),
                ('histopathologystatus', models.SmallIntegerField(choices=[(0, '未开始'), (1, '阅片中'), (2, '阅片完成')], default=0, verbose_name='阅片状态')),
                ('histodate', models.DateField(blank=True, null=True, verbose_name='阅片状态变更日期')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('observedby', models.ManyToManyField(blank=True, to='PAT.patusersinfo', verbose_name='参与人员')),
                ('studyno', models.ForeignKey(default=0, max_length=64, on_delete=django.db.models.deletion.DO_NOTHING, to='studys.anatomicalday', verbose_name='专题编号')),
            ],
            options={
                'verbose_name': '病理信息',
                'verbose_name_plural': '病理信息',
                'ordering': ['-update_time'],
            },
        ),
    ]
