# Generated by Django 2.2.2 on 2020-06-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersinfo',
            name='active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='usersinfo',
            name='jobid',
            field=models.IntegerField(default=10000, help_text='请输入工号', verbose_name='工号'),
        ),
    ]
