# Generated by Django 2.2.2 on 2020-06-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20200603_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersinfo',
            name='jobid',
            field=models.IntegerField(blank=True, help_text='请输入工号', verbose_name='工号'),
        ),
    ]
