# Generated by Django 2.2.2 on 2020-06-03 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0002_auto_20200603_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='tarcreates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infoname', models.CharField(max_length=256, verbose_name='培训主题')),
                ('infods', models.CharField(blank=True, max_length=256, null=True, verbose_name='描述')),
                ('addressroom', models.CharField(default='1128', max_length=256, unique=True, verbose_name='会议地点')),
                ('infodata', models.DateField(verbose_name='培训日期')),
                ('infotime', models.DateTimeField(verbose_name='开始时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ceratuser_id', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('infodept', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='assets.deptinfo', verbose_name='组织部门')),
                ('techname', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='assets.usersinfo', verbose_name='主讲人')),
            ],
            options={
                'verbose_name': '培训发起',
                'verbose_name_plural': '培训发起',
                'ordering': ['-update_time'],
            },
        ),
        migrations.CreateModel(
            name='tarinpope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entries', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('infoname', models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.DO_NOTHING, to='TRA.tarcreates', verbose_name='培训主题')),
                ('inpope', models.ManyToManyField(default=0, related_name='inuser_id', to='assets.usersinfo', verbose_name='应训人员')),
            ],
            options={
                'verbose_name': '应参培训人员',
                'verbose_name_plural': '应参培训人员',
                'ordering': ['-update_time'],
            },
        ),
        migrations.CreateModel(
            name='tarcheckpope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('checkpope', models.ManyToManyField(default=0, related_name='checkuser_id', to='assets.usersinfo', verbose_name='实训人员')),
                ('infoname', models.OneToOneField(max_length=256, on_delete=django.db.models.deletion.DO_NOTHING, to='TRA.tarcreates', verbose_name='培训主题')),
            ],
            options={
                'verbose_name': '实参培训人员',
                'verbose_name_plural': '实参培训人员',
                'ordering': ['-update_time'],
            },
        ),
        migrations.CreateModel(
            name='sendwxlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inpope', models.CharField(blank=True, max_length=10240, null=True, verbose_name='参加人员工号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('infoname', models.OneToOneField(max_length=256, on_delete=django.db.models.deletion.DO_NOTHING, to='TRA.tarinpope', verbose_name='培训主题')),
            ],
            options={
                'verbose_name': '通知日志',
                'verbose_name_plural': '通知日志',
                'ordering': ['-update_time'],
            },
        ),
    ]
