# Generated by Django 2.2.2 on 2020-06-03 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TRA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarcreates',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entriesceratuser_id', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='tarinpope',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entriesinuser_id', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
