# Generated by Django 2.2.2 on 2020-06-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRA', '0002_auto_20200603_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarcreates',
            name='infotime',
            field=models.TimeField(verbose_name='开始时间'),
        ),
    ]
