# Generated by Django 2.2.2 on 2020-06-03 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TRA', '0003_auto_20200603_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendwxlog',
            name='infoname',
            field=models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.DO_NOTHING, to='TRA.tarinpope', verbose_name='培训主题'),
        ),
        migrations.AlterField(
            model_name='tarcreates',
            name='addressroom',
            field=models.CharField(default='1128', max_length=256, verbose_name='会议地点'),
        ),
    ]
