# Generated by Django 2.2.2 on 2020-06-03 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20200603_1024'),
        ('TRA', '0004_auto_20200603_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendwxlog',
            name='infoname',
            field=models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.DO_NOTHING, to='TRA.tarcreates', verbose_name='培训主题'),
        ),
        migrations.AlterField(
            model_name='sendwxlog',
            name='inpope',
            field=models.CharField(blank=True, max_length=10240, null=True, verbose_name='信息接受人员'),
        ),
        migrations.CreateModel(
            name='msggrouptable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=128, verbose_name='组名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('grouppope', models.ManyToManyField(related_name='msgusergroup_id', to='assets.usersinfo', verbose_name='组成员')),
            ],
            options={
                'verbose_name': '负责人通知组',
                'verbose_name_plural': '负责人通知组',
                'ordering': ['-update_time'],
            },
        ),
    ]
