# Generated by Django 2.2.2 on 2020-06-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRA', '0005_auto_20200603_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendwxlog',
            name='class_from',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='信息发送类型'),
        ),
    ]
