# Generated by Django 2.2.2 on 2020-06-04 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TRA', '0006_sendwxlog_class_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarcreates',
            name='msgtogroup',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='TRA.msggrouptable', verbose_name='通知组'),
        ),
    ]
