# Generated by Django 2.2.2 on 2020-06-04 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TRA', '0007_tarcreates_msgtogroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarcheckpope',
            name='trainingduration',
            field=models.DecimalField(decimal_places=1, default=0.5, max_digits=3, verbose_name='培训时长'),
        ),
        migrations.AlterField(
            model_name='tarcreates',
            name='infodept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='assets.deptinfo', verbose_name='组织部门'),
        ),
        migrations.AlterField(
            model_name='tarcreates',
            name='techname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='assets.usersinfo', verbose_name='主讲人'),
        ),
    ]
