# Generated by Django 2.2.2 on 2019-12-24 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phasename', models.CharField(default='未设定', max_length=64, unique=True, verbose_name='阶段名称')),
            ],
            options={
                'verbose_name': '阶段名称',
                'verbose_name_plural': '阶段名称',
            },
        ),
        migrations.CreateModel(
            name='studyitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(default='未设定', max_length=64, unique=True, verbose_name='操作名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '试验操作名称',
                'verbose_name_plural': '试验操作名称',
            },
        ),
        migrations.CreateModel(
            name='studysinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studyno', models.CharField(default='未设定', max_length=128, unique=True, verbose_name='专题编号')),
                ('studyname', models.CharField(default='未设定', max_length=128, unique=True, verbose_name='专题名称')),
                ('anmailnum', models.PositiveSmallIntegerField(default=0, verbose_name='动物数量')),
                ('animalsource', models.CharField(default='未设定', max_length=128, verbose_name='动物来源')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('projectno', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='project.projectinfo', verbose_name='项目编号')),
                ('studydirector', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='assets.usersinfo', verbose_name='专题负责人')),
                ('testsystem', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='assets.testsystem', verbose_name='试验系统')),
            ],
            options={
                'verbose_name': '专题信息',
                'verbose_name_plural': '专题信息',
                'ordering': ['-update_time'],
            },
        ),
        migrations.CreateModel(
            name='studysprogressstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdappointdate', models.DateField(verbose_name='SD任命签发日期')),
                ('initiationdate', models.DateField(verbose_name='专题启动日期')),
                ('teststartdate', models.DateField(verbose_name='试验开始日期')),
                ('firstexposuredate', models.DateField(verbose_name='首次给药日期')),
                ('lastexposuredate', models.DateField(verbose_name='末次给药日期')),
                ('anatomicaldate', models.DateField(verbose_name='解剖日期')),
                ('testenddate', models.DateField(verbose_name='试验结束日期')),
                ('studycompletiondate', models.DateField(verbose_name='专题完成日期')),
                ('studystatus', models.SmallIntegerField(choices=[(0, '未完成'), (1, '终止'), (2, '进行中'), (3, '未开始')], default=0, verbose_name='专题状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('studyno', models.OneToOneField(default=0, max_length=64, on_delete=django.db.models.deletion.DO_NOTHING, to='studys.studysinfo', verbose_name='专题编号')),
            ],
            options={
                'verbose_name': '专题进展状态',
                'verbose_name_plural': '专题进展状态',
                'ordering': ['-update_time'],
            },
        ),
        migrations.CreateModel(
            name='studyproperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anmailnum', models.PositiveSmallIntegerField(default=1, verbose_name='动物数量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('studyno', models.OneToOneField(default=0, max_length=64, on_delete=django.db.models.deletion.DO_NOTHING, to='studys.studysinfo', verbose_name='专题编号')),
            ],
            options={
                'verbose_name': '专题属性',
                'verbose_name_plural': '专题属性',
                'ordering': ['-update_time'],
            },
        ),
        migrations.CreateModel(
            name='studyplansetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddwzljsd', models.PositiveSmallIntegerField(default=7, verbose_name='大动物资料接受日期')),
                ('gsbgd', models.PositiveSmallIntegerField(default=45, verbose_name='骨髓报告日期')),
                ('patd', models.PositiveSmallIntegerField(default=45, verbose_name='病理报告初稿日期')),
                ('tkadad', models.PositiveSmallIntegerField(default=45, verbose_name='TK/ADA报告日期')),
                ('sumrepd', models.PositiveSmallIntegerField(default=60, verbose_name='总结报告初稿日期')),
                ('wtfcfd', models.PositiveSmallIntegerField(default=65, verbose_name='委托方初稿/返还日期')),
                ('sdwtfcfd', models.PositiveSmallIntegerField(default=5, verbose_name='预计-委托方初稿/返还日期')),
                ('sendqad', models.PositiveSmallIntegerField(default=67, verbose_name='资料递交QA日期')),
                ('sdsendqad', models.PositiveSmallIntegerField(default=2, verbose_name='预计-资料递交QA日期')),
                ('qared', models.PositiveSmallIntegerField(default=80, verbose_name='QA返还日期')),
                ('sdqareturnd', models.PositiveSmallIntegerField(default=14, verbose_name='预计-QA返还日期')),
                ('finalrd', models.PositiveSmallIntegerField(default=90, verbose_name='终版报告签字日期')),
                ('sdfinalrd', models.PositiveSmallIntegerField(default=9, verbose_name='预计-终版报告签字日期')),
                ('activedd', models.PositiveSmallIntegerField(default=104, verbose_name='归档日期')),
                ('sdactivedd', models.PositiveSmallIntegerField(default=14, verbose_name='预计-归档日期')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('studyno', models.OneToOneField(default=0, max_length=64, on_delete=django.db.models.deletion.DO_NOTHING, to='studys.studysinfo', verbose_name='专题编号')),
            ],
            options={
                'verbose_name': '专题计划完成设定',
                'verbose_name_plural': '专题计划完成设定',
                'ordering': ['-update_time'],
            },
        ),
        migrations.CreateModel(
            name='studydays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptsdays', models.CharField(max_length=64, verbose_name='Pristima日程')),
                ('datedays', models.DateField(verbose_name='日程日期')),
                ('weekday', models.CharField(max_length=16, verbose_name='星期')),
                ('weekno', models.PositiveSmallIntegerField(default=1, verbose_name='周')),
                ('phasedays', models.CharField(max_length=64, verbose_name='试验阶段')),
                ('sex', models.CharField(max_length=16, verbose_name='性别')),
                ('itemactive', models.CharField(max_length=64, verbose_name='操作内容')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('itemname', models.ForeignKey(default=0, max_length=64, on_delete=django.db.models.deletion.DO_NOTHING, to='studys.studyitem', verbose_name='试验操作')),
                ('studyno', models.ForeignKey(default=0, max_length=64, on_delete=django.db.models.deletion.DO_NOTHING, to='studys.studysinfo', verbose_name='专题编号')),
            ],
            options={
                'verbose_name': '专题日程信息',
                'verbose_name_plural': '专题日程信息',
                'ordering': ['-update_time'],
            },
        ),
        migrations.CreateModel(
            name='sdmanager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biganimald', models.DateField(blank=True, null=True, verbose_name='大动物资料接受日期')),
                ('bmreportd', models.DateField(blank=True, null=True, verbose_name='骨髓报告日期')),
                ('patreportd', models.DateField(blank=True, null=True, verbose_name='病理报告初稿日期')),
                ('tkadareportd', models.DateField(blank=True, null=True, verbose_name='TK/ADA报告日期')),
                ('summaryreportd', models.DateField(blank=True, null=True, verbose_name='总结报告初稿日期')),
                ('returnd', models.DateField(blank=True, null=True, verbose_name='委托方初稿/返还日期')),
                ('dateqad', models.DateField(blank=True, null=True, verbose_name='资料递交QA日期')),
                ('qareturnd', models.DateField(blank=True, null=True, verbose_name=' QA返还日期')),
                ('Finalsignatured', models.DateField(blank=True, null=True, verbose_name=' 终版报告签字日期')),
                ('archived', models.DateField(blank=True, null=True, verbose_name='归档日期')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('studyno', models.OneToOneField(default=0, max_length=64, on_delete=django.db.models.deletion.DO_NOTHING, to='studys.studysinfo', verbose_name='专题编号')),
            ],
            options={
                'verbose_name': '毒理部专题管理',
                'verbose_name_plural': '毒理部专题管理',
                'ordering': ['-update_time'],
            },
        ),
        migrations.CreateModel(
            name='itemindept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deptitem', models.ManyToManyField(blank=True, to='studys.studyitem', verbose_name='试验项目')),
                ('deptname', models.OneToOneField(default=0, max_length=64, on_delete=django.db.models.deletion.DO_NOTHING, to='assets.deptinfo', verbose_name='部门名称')),
            ],
            options={
                'verbose_name': '部门试验操作关系',
                'verbose_name_plural': '部门试验操作关系',
            },
        ),
        migrations.CreateModel(
            name='anatomicalday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.DateField(verbose_name='解剖日期')),
                ('anmailnum', models.PositiveSmallIntegerField(default=1, verbose_name='动物数量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('phasename', models.ForeignKey(default=0, max_length=64, on_delete=django.db.models.deletion.DO_NOTHING, to='studys.phase', verbose_name='阶段')),
                ('studyno', models.ForeignKey(default=0, max_length=64, on_delete=django.db.models.deletion.DO_NOTHING, to='studys.studysinfo', verbose_name='专题编号')),
            ],
            options={
                'verbose_name': '解剖日程',
                'verbose_name_plural': '解剖日程',
                'ordering': ['-update_time'],
            },
        ),
    ]
