# Generated by Django 2.2.2 on 2020-03-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyplansetting',
            name='activedd',
            field=models.PositiveSmallIntegerField(default=104, verbose_name='归档天'),
        ),
        migrations.AlterField(
            model_name='studyplansetting',
            name='ddwzljsd',
            field=models.PositiveSmallIntegerField(default=7, verbose_name='大动物资料接受天'),
        ),
        migrations.AlterField(
            model_name='studyplansetting',
            name='finalrd',
            field=models.PositiveSmallIntegerField(default=90, verbose_name='终版报告签字天'),
        ),
        migrations.AlterField(
            model_name='studyplansetting',
            name='gsbgd',
            field=models.PositiveSmallIntegerField(default=45, verbose_name='骨髓报告天'),
        ),
        migrations.AlterField(
            model_name='studyplansetting',
            name='patd',
            field=models.PositiveSmallIntegerField(default=45, verbose_name='病理报告初稿天'),
        ),
        migrations.AlterField(
            model_name='studyplansetting',
            name='qared',
            field=models.PositiveSmallIntegerField(default=80, verbose_name='QA返还天'),
        ),
        migrations.AlterField(
            model_name='studyplansetting',
            name='sdactivedd',
            field=models.PositiveSmallIntegerField(default=14, verbose_name='预计-归档天'),
        ),
        migrations.AlterField(
            model_name='studyplansetting',
            name='sdfinalrd',
            field=models.PositiveSmallIntegerField(default=9, verbose_name='预计-终版报告签字天'),
        ),
        migrations.AlterField(
            model_name='studyplansetting',
            name='sdqareturnd',
            field=models.PositiveSmallIntegerField(default=14, verbose_name='预计-QA返还天'),
        ),
        migrations.AlterField(
            model_name='studyplansetting',
            name='sdsendqad',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='预计-资料递交QA天'),
        ),
        migrations.AlterField(
            model_name='studyplansetting',
            name='sdwtfcfd',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='预计-委托方初稿/返还天'),
        ),
        migrations.AlterField(
            model_name='studyplansetting',
            name='sendqad',
            field=models.PositiveSmallIntegerField(default=67, verbose_name='资料递交QA天'),
        ),
        migrations.AlterField(
            model_name='studyplansetting',
            name='sumrepd',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='总结报告初稿天'),
        ),
        migrations.AlterField(
            model_name='studyplansetting',
            name='tkadad',
            field=models.PositiveSmallIntegerField(default=45, verbose_name='TK/ADA报告天'),
        ),
        migrations.AlterField(
            model_name='studyplansetting',
            name='wtfcfd',
            field=models.PositiveSmallIntegerField(default=65, verbose_name='委托方初稿/返还天'),
        ),
    ]
