# Generated by Django 2.2.2 on 2019-12-24 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliusersinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='用户名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'CLI用户信息',
                'verbose_name_plural': 'CLI用户信息',
            },
        ),
        migrations.CreateModel(
            name='clireading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anmailnum', models.PositiveSmallIntegerField(default=0, verbose_name='动物数量')),
                ('bonemarrow', models.SmallIntegerField(choices=[(0, '不制片'), (1, '制片')], default=0, verbose_name='骨髓制片')),
                ('readingstatus', models.SmallIntegerField(choices=[(0, '不阅片'), (1, '待阅片'), (2, '阅片中'), (3, '阅片完成'), (4, '待定')], default=0, verbose_name='阅片状态')),
                ('readingdate', models.DateField(blank=True, null=True, verbose_name='阅片日期')),
                ('reportdate', models.DateField(blank=True, null=True, verbose_name='报告日期')),
                ('inputdate', models.DateField(blank=True, null=True, verbose_name='归档日期')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('observedby', models.ManyToManyField(to='CLI.cliusersinfo', verbose_name='阅片人员')),
                ('studyno', models.ForeignKey(default=0, max_length=64, on_delete=django.db.models.deletion.DO_NOTHING, to='studys.studysinfo', verbose_name='专题编号')),
            ],
            options={
                'verbose_name': '临检阅片',
                'verbose_name_plural': '临检阅片',
                'ordering': ['-update_time'],
            },
        ),
        migrations.CreateModel(
            name='cliitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('anmailnum', models.PositiveSmallIntegerField(default=0, verbose_name='动物数量')),
                ('cbaitem', models.PositiveSmallIntegerField(default=0, verbose_name='CBA')),
                ('urinarysediment', models.PositiveSmallIntegerField(default=0, verbose_name='尿沉渣')),
                ('flowcytometry', models.PositiveSmallIntegerField(default=0, verbose_name='流式')),
                ('hematology', models.PositiveSmallIntegerField(default=0, verbose_name='血液学')),
                ('biochemistry', models.PositiveSmallIntegerField(default=0, verbose_name='生化')),
                ('coagulation', models.PositiveSmallIntegerField(default=0, verbose_name='凝血')),
                ('urinaryroutine', models.PositiveSmallIntegerField(default=0, verbose_name='尿常规')),
                ('pagt', models.PositiveSmallIntegerField(default=0, verbose_name='PAgT')),
                ('bonemarrowsmear', models.PositiveSmallIntegerField(default=0, verbose_name='骨髓涂片')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('remarks1', models.TextField(blank=True, null=True, verbose_name='注意1')),
                ('remarks2', models.TextField(blank=True, null=True, verbose_name='注意2')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('dutyofficer', models.ManyToManyField(to='CLI.cliusersinfo', verbose_name='值班人员')),
                ('studyno', models.ForeignKey(default=0, max_length=64, on_delete=django.db.models.deletion.DO_NOTHING, to='studys.studysinfo', verbose_name='专题编号')),
            ],
            options={
                'verbose_name': '临检项目',
                'verbose_name_plural': '临检项目',
                'ordering': ['-update_time'],
            },
        ),
    ]
