# Generated by Django 2.2.2 on 2019-12-24 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkingitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkname', models.CharField(default='未设定', max_length=256, unique=True, verbose_name='项目名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '检查项目',
                'verbose_name_plural': '检查项目',
                'ordering': ['-update_time'],
            },
        ),
        migrations.CreateModel(
            name='qauusersinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='用户名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'QAU用户信息',
                'verbose_name_plural': 'QAU用户信息',
            },
        ),
        migrations.CreateModel(
            name='checkingplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkdate', models.DateField(verbose_name='检查日期')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('checkitem', models.ManyToManyField(max_length=256, to='QAU.checkingitem', verbose_name='检查项目')),
                ('person', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='QAU.qauusersinfo', verbose_name='责任人')),
                ('studyno', models.ForeignKey(default=0, max_length=64, on_delete=django.db.models.deletion.DO_NOTHING, to='studys.studysinfo', verbose_name='专题编号')),
            ],
            options={
                'verbose_name': '检查计划',
                'verbose_name_plural': '检查计划',
                'ordering': ['-update_time'],
            },
        ),
    ]
