dayset =   {'ddwzljsd':7,
            'gsbgd':45,
            'patd':45,
            'tkadad':45,
            'sumrepd':60,
            'wtfcfd':65,
            'sdwtfcfd':5,
            'sendqad':67,
            'sdsendqad':2,
            'qared':80,
            'sdqareturnd':14,
            'finalrd':90,
            'sdfinalrd':9,
            'activedd':104,
            'sdactivedd':14
                      }  # 宗老师设定时间参数