# Generated by Django 2.2.2 on 2020-03-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testarticleinfo',
            name='testtrarticleapi',
            field=models.FloatField(blank=True, max_length=128, null=True, verbose_name='供试品API-%'),
        ),
        migrations.AddField(
            model_name='testarticleinfo',
            name='testtrarticlepcs',
            field=models.FloatField(blank=True, max_length=128, null=True, verbose_name='每pcs含量'),
        ),
    ]
